### ISSUE TITLE
[-] Could not upload video, retrying...

### ISSUE THREAD

**Issue by jmieyt** [xXChezyXx/TikTok-AutoUpload#6]
![image](https://github.com/xXChezyXx/TikTok-AutoUpload/assets/77451272/a9070c6f-586a-44ac-9dbe-6fd06eda4d38)

**Comment by jmieyt** [comment]
C:\Users\joyce\Downloads\TikTok-AutoUpload-main\TikTok-AutoUpload-main>py tiktok_autoupload.py -s SESSION -v xideo.mp4 -t xd
Traceback (most recent call last):
  File "C:\Users\joyce\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joyce\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joyce\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joyce\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joyce\Downloads\TikTok-AutoUpload-main\TikTok-AutoUpload-main\tiktok_autoupload.py", line 293, in <module>
    upload_video(args.sessionid, args.video, args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "C:\Users\joyce\Downloads\TikTok-AutoUpload-main\TikTok-AutoUpload-main\tiktok_autoupload.py", line 254, in upload_video
    if r.json()["status_msg"] == "You are posting too fast. Take a rest.":
       ^^^^^^^^
  File "C:\Users\joyce\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0


Here the Error i got after i used the Exception right.

**Comment by xChezY** [comment]
Normalerweise sollte der Exception garnicht aufgeruft werden wegen try und except...
Hast du den Code irgendwie modifiziert oder umgeändert? Falls nicht, kannst du dann die Zeile umändern von
```
r.json()["status_msg"] == "You are posting too fast. Take a rest.":
```
zu 
```
print(r.text)
r.json()["status_msg"] == "You are posting too fast. Take a rest.":
```

und dann mir den Output davon senden?

**Comment by jmieyt** [comment]
Da wird nur dass gespammt, deshalb hab ich mir die Exception einfach selber ausgegeben

"[-] Could not upload video, retrying..."

**Comment by xChezY** [comment]
Achso, ja das Programm würde ich sagen ist ein bisschen ineffizient, weswegen das solange gespammt wird, bis das Video hochgeladen wird. Es braucht so zwischen 3 bis 60 Versuche. Frag nicht, warum das so von TikTok ist. Bin gerade dabei eine alternative Lösung zu finden. Sag Bescheid, sollte es nach den 60 Versuchen immer noch nicht klappen
